import type { KnowledgeFact, KnowledgeObject } from "@/lib/property-twin/types";

import type { PropertyFaq } from "./types";

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function generateFaqsFromKnowledge(
  propertyId: string,
  objects: KnowledgeObject[],
  facts: KnowledgeFact[],
): PropertyFaq[] {
  const faqs: PropertyFaq[] = [];
  const now = new Date().toISOString();

  for (const object of objects) {
    const objectFacts = facts.filter(
      (f) => f.knowledgeObjectId === object.id && f.verificationLevel !== "retired",
    );

    if (objectFacts.length === 0 && object.summary) {
      faqs.push({
        id: `faq-${slugify(object.name)}-overview`,
        propertyId,
        question: `Tell me about the ${object.name}.`,
        answer: object.summary,
        knowledgeObjectIds: [object.id],
        factKeys: [],
        autoGenerated: true,
        updatedAt: now,
      });
      continue;
    }

    for (const fact of objectFacts.slice(0, 3)) {
      faqs.push({
        id: `faq-${slugify(object.name)}-${slugify(fact.factKey)}`,
        propertyId,
        question: `What is the ${object.name} ${fact.factKey.replace(/_/g, " ")}?`,
        answer: `${object.name}: ${fact.factValue}`,
        knowledgeObjectIds: [object.id],
        factKeys: [fact.factKey],
        autoGenerated: true,
        updatedAt: now,
      });
    }
  }

  return faqs;
}

export function refreshFaqForFactChange(
  faqs: PropertyFaq[],
  objectId: string,
  factKey: string,
  newValue: string,
): PropertyFaq[] {
  return faqs.map((faq) => {
    if (!faq.knowledgeObjectIds.includes(objectId) || !faq.factKeys.includes(factKey)) {
      return faq;
    }
    return {
      ...faq,
      answer: faq.answer.replace(/: .+$/, `: ${newValue}`),
      updatedAt: new Date().toISOString(),
    };
  });
}
