import type { KnowledgeCategory, KnowledgeSource, VerificationLevel } from "@/types/database";

export type FactType =
  | "text"
  | "number"
  | "boolean"
  | "currency"
  | "date"
  | "measurement"
  | "percentage"
  | "choice"
  | "url"
  | "document"
  | "photo"
  | "video"
  | "location"
  | "timeline_event"
  | "relationship";

export interface KnowledgeSearchResult {
  type: "object" | "fact" | "timeline" | "document";
  id: string;
  title: string;
  subtitle: string | null;
  score: number;
  category?: KnowledgeCategory;
}

export interface KnowledgeHealthScore {
  overall: number;
  knowledgeCoverage: number;
  verificationScore: number;
  conflictScore: number;
  relationshipScore: number;
  documentCoverage: number;
  photoCoverage: number;
  timelineCoverage: number;
  missingItems: string[];
  suggestions: string[];
}

export interface PropertyFaq {
  id: string;
  propertyId: string;
  question: string;
  answer: string;
  knowledgeObjectIds: string[];
  factKeys: string[];
  autoGenerated: boolean;
  updatedAt: string;
}

export interface FactValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export interface AiKnowledgeBundle {
  objects: Array<{
    id: string;
    name: string;
    category: KnowledgeCategory;
    summary: string | null;
    facts: Array<{
      key: string;
      value: string;
      verificationLevel: VerificationLevel;
      source: KnowledgeSource;
    }>;
  }>;
  policies: string[];
  hasVerifiedData: boolean;
}

export interface KnowledgeSuggestion {
  type:
    | "missing_fact"
    | "duplicate_fact"
    | "conflicting_fact"
    | "related_fact"
    | "upload_recommended"
    | "voice_note_recommended"
    | "buyer_question"
    | "faq_suggested";
  message: string;
  priority: number;
  metadata: Record<string, unknown>;
}
